/**
 * @license
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */
// Generated stylesheet for ./menu/internal/menu-styles.css.
import { css } from 'lit';
export const styles = css `:host{--wd-elevation-level: var(--wd-menu-container-elevation, 2);--wd-elevation-shadow-color: var(--wd-menu-container-shadow-color, var(--wd-sys-color-shadow, #000));min-width:112px;color:unset;display:contents}wd-focus-ring{--wd-focus-ring-shape: var(--wd-menu-container-shape, var(--wd-sys-shape-corner-extra-small, 4px))}.menu{border-radius:var(--wd-menu-container-shape, var(--wd-sys-shape-corner-extra-small, 4px));display:none;inset:auto;border:none;padding:0px;overflow:visible;background-color:rgba(0,0,0,0);color:inherit;opacity:0;z-index:20;position:absolute;user-select:none;max-height:inherit;height:inherit;min-width:inherit;max-width:inherit;scrollbar-width:inherit}.menu::backdrop{display:none}.fixed{position:fixed}.items{display:block;list-style-type:none;margin:0;outline:none;box-sizing:border-box;background-color:var(--wd-menu-container-color, var(--wd-sys-color-surface-container, #f3edf7));height:inherit;max-height:inherit;overflow:auto;min-width:inherit;max-width:inherit;border-radius:inherit;scrollbar-width:inherit}.item-padding{padding-block:var(--wd-menu-top-space, 8px) var(--wd-menu-bottom-space, 8px)}.has-overflow:not([popover]) .items{overflow:visible}.has-overflow.animating .items,.animating .items{overflow:hidden}.has-overflow.animating .items{pointer-events:none}.animating ::slotted(.wd-menu-hidden){opacity:0}slot{display:block;height:inherit;max-height:inherit}::slotted(:is(wd-divider,[role=separator])){margin:8px 0}@media(forced-colors: active){.menu{border-style:solid;border-color:CanvasText;border-width:1px}}
`;
//# sourceMappingURL=menu-styles.js.map